// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsnltdnllizoksohapqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzbmx0ZG5sbGl6b2tzb2hhcHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDE1NDAsImV4cCI6MjA2NDg3NzU0MH0._HPSMEweQf2tfMaM5BIyAvq--oZhp6yvhN6LN1qioh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);